/* UI and persistence. Rendering never draws an event or consumes random state. */
'use strict';
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Math.round(n).toLocaleString('ko-KR');
const STORE='hpn-v2-run',META='hpn-v2-meta';
let storageOK=true;
function read(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(e){storageOK=false;return fallback;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch(e){storageOK=false;}}
let raw=read(STORE,null),s=HP.valid(raw)?raw:null;
const m=read(META,{});let meta={best:Math.max(0,Number(m?.best)||0),found:Array.isArray(m?.found)?m.found.filter(n=>HP.COMBOS.some(c=>c.n===n)):[],finished:Array.isArray(m?.finished)?m.finished.filter(Number.isInteger).slice(-30):[],plays:Number(m?.plays)||0,sound:m?.sound===true,reduced:m?.reduced===true};
let screen='home',busy=false,pending=null,context=null,toastTimer,swipe=null,focusBefore=null;
const motion=()=>meta.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;
function persist(){write(STORE,s);write(META,meta);document.body.classList.toggle('reduced',meta.reduced);}
function seed(){let x=new Uint32Array(1);if(globalThis.crypto?.getRandomValues)crypto.getRandomValues(x);else x[0]=(Date.now()^Math.floor(Math.random()*4294967296))>>>0;return x[0];}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hide');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hide'),2200);}
function beep(type){if(!meta.sound)return;try{context=context||new (window.AudioContext||window.webkitAudioContext)();context.resume();const ns=type==='combo'?[392,523,659,784]:type==='critical'?[523,659,784,1047]:type==='fail'?[185,139]:[440,554];ns.forEach((f,i)=>{let o=context.createOscillator(),g=context.createGain(),t=context.currentTime+i*.055;o.type='sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.06,t+.014);g.gain.exponentialRampToValueAtTime(.0001,t+.19);o.connect(g);g.connect(context.destination);o.start(t);o.stop(t+.20);});}catch(e){}}
function burst(){if(motion())return;for(let i=0;i<20;i++){const el=document.createElement('i');el.className='particle';el.style.setProperty('--c',['#7c9e43','#f0bf50','#99c896','#e28d61'][i%4]);el.style.setProperty('--x',`${Math.sin(i*2.4)*(110+i*6)}px`);el.style.setProperty('--y',`${Math.cos(i*2.4)*120+100}px`);document.body.append(el);setTimeout(()=>el.remove(),850);}}
function header(){return `<header class="top"><div class="brand"><span class="logo" aria-hidden="true">H</span><span>인류 패치노트<br><span class="smallcap">PATCH LAB · v2.0</span></span></div><div class="topright">${screen==='game'?'<button class="iconbtn" data-act="home" aria-label="저장하고 처음으로">⌂</button>':''}<button class="iconbtn" data-act="settings" aria-label="설정과 도움말">⚙</button></div></header>`;}
function globe(){return '<div class="orbit" aria-hidden="true"><div class="globe"><span class="face">• •</span></div><span class="sat a">🌱</span><span class="sat b">🤖</span><span class="sat c">×2</span></div>';}
function home(){screen='home';busy=false;const resume=s&&s.phase!=='end';$('app').innerHTML=`<section class="screen">${header()}<div class="homehero"><span class="eyebrow">SWIPE. PATCH. BOOM.</span><h1>인류를 고치다.<br><em>우주까지 망치다.</em></h1><p>규칙을 섞고, 점수를 터뜨리세요.</p>${globe()}<div class="homefacts"><span><b>18</b>번의 선택</span><span><b>12</b>개의 규칙</span><span><b>10</b>가지 조합</span></div></div><button class="primary" data-act="${resume?'resume':'new'}">${resume?'이어하기 · '+(s.turn+1)+'/18':'인류 업데이트 시작'} →</button>${resume?'<button class="secondary" data-act="new">새 실험</button>':''}<div class="homelinks"><button class="linkbutton" data-act="collection">조합 도감 ${meta.found.length}/10</button><span>내 최고 ${fmt(meta.best)}</span><a href="./classic.html">이전 버전</a></div><div class="footnote">광고·결제 없음 · 기록은 이 브라우저에만 저장${storageOK?'':'<br>현재 저장이 차단되어 이어하기가 제한됩니다.'}</div></section>`;}
function newGame(){s=HP.fresh(seed());meta.plays++;persist();screen='game';render();}
function detail(id,lv=1){const d={photo:`자연 점수 ×${(1.4+lv*.4).toFixed(1)}`,robots:`과학 점수 ×${(1.4+lv*.4).toFixed(1)}`,immortal:`실패 피해 −${7*lv}`,solar:`성공 에너지 +${5*lv}`,tiny:`실험 에너지 비용 −${5*lv}`,nosleep:`실험 점수 ×${(1.3+lv*.3).toFixed(1)}`,hive:`과학 성공률 +${15*lv}%p`,portal:`모든 점수 ×${(1+.25*lv).toFixed(2)}`,holiday:`안전 선택 체력 +${6*lv}`,truth:`안전 점수 ×${(1.3+.4*lv).toFixed(1)}`,bliss:`성공 체력 +${4*lv}`,luck:`실험 성공률 +${10*lv}%p`};return d[id];}
function ruleStrip(){return `<div class="rules">${[0,1,2].map(i=>{const r=s.rules[i];return r?`<button class="rule" data-act="rule" data-id="${r.id}" aria-label="${esc(HP.RULES[r.id].n)} 레벨 ${r.lv}, 효과 보기"><span class="ri">${HP.RULES[r.id].i}</span><span class="rn">${HP.RULES[r.id].n}</span><span class="lv">Lv.${r.lv}</span></button>`:'<button class="rule empty" data-act="collection"><span class="ri">＋</span><span class="rn">규칙 슬롯</span></button>';}).join('')}</div>`;}
function hud(){const era=Math.min(2,Math.floor(s.turn/6)),goal=HP.GOALS[era],cs=HP.combos(s);return `<section class="scorepanel" aria-label="문명 상태"><div class="scorehead"><span>문명 점수</span><span>${era+1}단계 · ${s.turn+1}/18</span></div><div class="score">${fmt(s.score)}</div><div class="meters">${[['hp','♥ 체력'],['energy','⚡ 에너지']].map(([k,n])=>`<div class="meter ${k} ${s[k]<24?'low':''}"><div class="labels"><span>${n}</span><b>${s[k]}<small>/100</small></b></div><div class="bar"><i style="width:${s[k]}%"></i></div></div>`).join('')}</div></section><div class="goal"><div class="goalrow"><span>${['🌑 정전','☄️ 자원','🛸 문명 심사'][era]} · 목표 ${fmt(goal)}</span><span>${fmt(s.stageScore)} / ${fmt(goal)}</span></div><div class="bar"><i style="width:${Math.min(100,s.stageScore/goal*100)}%"></i></div><div class="route" aria-label="단계 진행 ${s.turn%6+1}/6">${[0,1,2,3,4,5].map(i=>`<span class="${i<s.turn%6?'done':i===s.turn%6?'now':i===5?'boss':''}"></span>`).join('')}</div></div>${ruleStrip()}<div class="comboBar">${cs.length?cs.map(c=>c.i+' '+c.n).join(' · ')+' <b>×'+2**cs.length+'</b>':'규칙 2개를 맞추면 조합 ×2'}</div>`;}
function draftCard(){const c=s.current;return `<article class="card" id="playcard"><div class="cardtop"><span>🧬 규칙 설치</span><span>영구 유지 · 최대 3개</span></div><h2>인류에 무엇을 넣을까?</h2><div class="choices">${c.ids.map((id,side)=>{const r=HP.RULES[id],lv=HP.level(s,id)+1,newCombo=HP.COMBOS.some(c=>(c.a===id&&HP.level(s,c.b))||(c.b===id&&HP.level(s,c.a)));return `<button class="choice ${side?'risk':''}" data-act="choose" data-side="${side}"><span class="chicon">${r.i}</span><span class="label">${r.n}</span><span class="desc">${detail(id,lv)}</span><span class="combohint">${lv>1?'레벨 업 → Lv.'+lv:newCombo?'조합 가능! ×2':'새 규칙'}</span></button>`;}).join('')}</div><div class="chanceLine">${c.recommended?'현재 규칙과 맞는 조합 후보를 포함했습니다.':'설치 후에는 이 규칙이 점수와 확률을 바꿉니다.'}</div></article>`;}
function eventCard(){const c=s.current,boss=c.kind==='boss',r=c.row,tag=boss?r[4]:r[0],title=boss?r[0]:r[1],icon=boss?r[1]:r[2];const p0=HP.preview(s,0),p1=HP.preview(s,1);return `<article class="card" id="playcard"><div class="cardtop"><span class="tag ${tag}">${{bio:'🌱 자연',tech:'⚙ 과학',life:'♥ 생활'}[tag]}</span><span>${boss?'위기 판정 · 미달 체력 −24':c.boost?'💥 폭주 사건 · 점수 ×2':'확정 보상? 큰 실험?'}</span></div><div class="eventicon" aria-hidden="true">${icon}</div><h2>${title}</h2><div class="choices">${[p0,p1].map((p,side)=>`<button class="choice ${side?'risk':''}" data-act="choose" data-side="${side}" ${s.energy<p.cost?'disabled':''}><span class="label">${boss?r[2+side]:r[3+side]}</span><span class="gain">+${fmt(p.gain)}</span><small>${side?'대성공 +'+fmt(p.gain*3):'확정 보상'}</small><span class="cost">${side?'⚡ −'+p.cost:'⚡ +13 · ♥ +'+(p.hp+HP.level(s,'bliss')*4)}</span>${side?`<div class="prob" aria-hidden="true"><i class="crit" style="width:10%"></i><i style="width:${p.p-10}%"></i><i class="bad" style="width:${100-p.p}%"></i></div><small>성공 ${p.p}% · 실패 시 ♥ −${p.damage}</small>`:'<small>확률 100% · 안전 선택</small>'}</button>`).join('')}</div><div class="chanceLine">실험: 대성공 10% + 일반 성공 ${p1.p-10}% + 실패 ${100-p1.p}%</div></article>`;}
function resultCard(){const l=s.last;if(l.kind==='draft'){const r=HP.RULES[l.id];return `<article class="card resultcard" aria-live="polite"><div class="resultlabel">${l.newCombos.length?'조합 완성!':l.upgrade?'레벨 업!':'패치 설치 완료'}</div><div class="resulticon">${r.i}</div><h2>${r.n} <small>Lv.${HP.level(s,l.id)}</small></h2><p class="resultline">${detail(l.id,HP.level(s,l.id))}</p>${l.newCombos.map(n=>`<div class="comboresult">${esc(n)} · 모든 점수 ×2</div>`).join('')}<button class="primary" data-act="next">적용된 세계로 →</button></article>`;}
 const p=l.pr,cp=l.checkpoint;return `<article class="card resultcard ${l.critical?'critical':l.ok?'':'fail'}" aria-live="polite"><div class="resultlabel">${l.critical?'대성공! ×3':l.ok?'패치 성공':'패치 실패'}</div><div class="biggain">${l.ok?'+'+fmt(l.gain):'♥ −'+p.damage}</div><div class="math">${l.ok?`<span>기본 ${fmt(p.base)}</span>${p.steps.map(v=>`<span>${v.n} ×${Number(v.m.toFixed(2))}</span>`).join('')}${l.critical?'<span>대성공 ×3</span>':''}`:`<span>성공률 ${p.p}% · 실패 ${100-p.p}%</span>`}</div><p class="resultline">${esc(l.line)}</p>${l.roll?`<span class="muted">판정 ${l.roll}/100 · ${l.roll<=10?'10 이하면 대성공':l.roll<=p.p?p.p+' 이하면 성공':p.p+' 초과로 실패'}</span>`:''}${cp?`<div class="comboresult">${cp.pass?'위기 통과 · ♥ +10 · ⚡ +15':'목표 미달 · ♥ −24'}<br><small>${fmt(cp.score)} / ${fmt(cp.goal)}</small></div>`:''}<button class="primary" data-act="next">${s.hp<=0||s.turn===17?'내 문명 결과 보기':cp?'다음 시대 →':'다음 패치 →'}</button></article>`;}
function animateResult(){if(motion()||s.phase!=='result'||!s.last.ok)return;const target=s.last.gain,score=s.score,el=document.querySelector('.biggain'),total=document.querySelector('.score');const start=performance.now();function frame(t){if(!el?.isConnected)return;const k=Math.min(1,(t-start)/520),ease=1-Math.pow(1-k,3);el.textContent='+'+fmt(target*ease);if(total?.isConnected)total.textContent=fmt(score-target+target*ease);if(k<1)requestAnimationFrame(frame);}requestAnimationFrame(frame);}
function render(){if(screen==='home')return home();if(!s)return home();if(s.phase==='end')return ending();screen='game';$('app').innerHTML=`<section class="screen">${header()}${hud()}${s.phase==='result'?resultCard():s.current.kind==='draft'?draftCard():eventCard()}<div class="tools"><button class="tool" data-act="reroll" ${s.phase!=='choose'||s.rerolls===0||s.current.kind==='boss'?'disabled':''}>↻ 새 후보 ${s.rerolls}/2</button><button class="tool" data-act="undo" ${!s.prev||s.undoUsed?'disabled':''}>↶ 되돌리기 ${s.undoUsed?'0':'1'}/1</button><button class="tool" data-act="collection">조합 도감</button></div></section>`;bindSwipe();animateResult();}
function endingInfo(){const c=HP.COMBOS.find(c=>s.found.includes(c.n));return {name:s.hp<=0?'문명 재부팅 필요':s.clears===3?(c?c.n:'우주 진출 인류'):s.clears===2?'아슬아슬한 유토피아':'일단 살아남은 인류',icon:s.hp<=0?'💥':s.clears===3?'🌌':'🌍',grade:s.hp<=0?'실험 중단':s.clears===3?'S · 모든 위기 통과':s.clears===2?'A · 두 위기 통과':'B · 다음 실험을 기약'};}
function finalize(){meta.found=[...new Set([...meta.found,...s.found])];meta.best=Math.max(meta.best,s.score);if(!meta.finished.includes(s.seed))meta.finished=[...meta.finished.slice(-29),s.seed];persist();}
function ending(){screen='game';finalize();const e=endingInfo();$('app').innerHTML=`<section class="screen">${header()}<div class="endhero"><span class="eyebrow">${e.grade}</span><span class="badge">${e.icon}</span><h1>${e.name}</h1><div class="endscore">${fmt(s.score)}</div><span class="smallcap">CIVILIZATION SCORE</span><div class="endgrid"><div><strong>${s.turn}/18</strong>완료한 선택</div><div><strong>${s.clears}/3</strong>위기 통과</div><div><strong>${fmt(s.peak)}</strong>한 번에 얻은 최고 점수</div></div><div class="endrules">${s.rules.map(r=>`<span>${HP.RULES[r.id].i} ${HP.RULES[r.id].n} Lv.${r.lv}</span>`).join('')}</div><p class="muted">다음엔 어떤 규칙 두 개를 섞어볼까요?</p></div><button class="primary" data-act="new">다른 인류 만들어보기 →</button><div class="smallactions"><button class="secondary" data-act="share">결과 공유</button><button class="secondary" data-act="collection">도감 ${meta.found.length}/10</button></div><p class="footnote">실험 코드 ${s.seed.toString(36).toUpperCase()} · 최고 ${fmt(meta.best)}<br>순위는 서버에 전송하지 않습니다.</p></section>`;}
function modal(title,body){focusBefore=document.activeElement;$('dialog').innerHTML=`<div class="sheethead"><h2>${title}</h2><button class="close" data-act="close" aria-label="닫기">×</button></div>${body}`;$('dialog').showModal();}
function close(){pending=null;$('dialog').close();focusBefore?.focus?.();}
function collection(){const found=new Set([...meta.found,...(s?.found||[])]);modal(`조합 도감 ${found.size}/10`,`<p class="muted">두 규칙이 함께 설치되어 있으면 모든 점수 ×2.<br>조합이 두 개면 ×4. 교체하면 해당 조합은 해제됩니다.</p>${HP.COMBOS.map(c=>`<div class="recipe"><span><b>${found.has(c.n)?'✓ ':''}${c.n}</b><small>${HP.RULES[c.a].n} + ${HP.RULES[c.b].n}</small></span><span class="ico">${c.i}</span></div>`).join('')}`);}
function showRule(id){if(!HP.RULES[id])return;const lv=s?HP.level(s,id):1;modal(HP.RULES[id].i+' '+HP.RULES[id].n,`<p><b>${detail(id,lv||1)}</b></p><p class="muted">같은 규칙을 다시 고르면 레벨 업. 최대 Lv.3.<br>성공률은 최대 95%, 실험 비용은 최소 3입니다.</p>${HP.COMBOS.filter(c=>c.a===id||c.b===id).map(c=>`<div class="recipe"><span>${c.i} ${c.n}<small>+ ${HP.RULES[c.a===id?c.b:c.a].n}</small></span><b>×2</b></div>`).join('')}`);}
function settings(){modal('실험실 설정',`<div class="setting"><span>효과음</span><button data-act="sound">${meta.sound?'켜짐':'꺼짐'}</button></div><div class="setting"><span>움직임 줄이기</span><button data-act="motion">${meta.reduced?'켜짐':'시스템 설정'}</button></div><p><b>왼쪽은 안전, 오른쪽은 실험.</b><br>실험의 대성공·성공·실패 확률은 선택지에 표시됩니다. 에너지가 모자라면 안전 선택으로 충전하세요.</p><p>6번마다 위기 심사. 단계 점수 목표를 넘기면 체력 +10, 에너지 +15. 미달이면 체력 −24입니다. 체력 0은 종료, 에너지 0은 종료가 아닙니다.</p><p>새 후보는 한 판에 2번, 되돌리기는 1번. 되돌린 뒤 같은 선택은 같은 판정이 나옵니다. 카드를 좌우로 밀거나 ← → / 1 2 키로 선택하세요.</p><p class="muted">규칙 후보는 조합 가능성을 높여 제시합니다. 4번째 선택 이후 일반 사건은 14% 확률로 점수 2배인 폭주 사건이 됩니다. 카드 판정은 공개된 확률 그대로이며 유료 확률 조작은 없습니다.</p><p class="muted">진행과 최고 기록만 이 브라우저에 저장합니다. 외부 분석 도구·광고·로그인·결제는 없습니다. 새 버전은 이전 버전 저장과 별도로 관리됩니다.</p><button class="secondary" data-act="export">내 플레이 기록 JSON 저장</button>`);}
function choose(side,rep){if(busy||screen!=='game'||!s||s.phase!=='choose')return;const out=HP.choose(s,side,rep);if(out?.replace){pending=side;modal('어떤 규칙을 뺄까요?',`<p class="muted">${HP.RULES[out.id].i} ${HP.RULES[out.id].n} 설치 · 기존 레벨은 사라집니다.</p>${s.rules.map(r=>`<button class="replace" data-act="replace" data-id="${r.id}"><em>${HP.RULES[r.id].i}</em><span><b>${HP.RULES[r.id].n} Lv.${r.lv}</b><br><small>${detail(r.id,r.lv)}</small></span></button>`).join('')}<button class="secondary" data-act="close">선택 취소</button>`);return;}if(out!==true)return;busy=true;persist();render();const l=s.last;beep(l.kind==='draft'&&l.newCombos.length?'combo':l.critical?'critical':l.ok===false?'fail':'ok');if(l.critical||l.newCombos?.length)burst();$('announce').textContent=l.kind==='draft'?'규칙 설치 완료':l.ok?`${fmt(l.gain)}점 획득`:'실험 실패';setTimeout(()=>{busy=false;},motion()?80:240);}
function next(){if(busy||!s||screen!=='game')return;if(HP.advance(s)){persist();render();}}
function bindSwipe(){const el=$('playcard');if(!el)return;el.addEventListener('pointerdown',e=>{if(e.target.closest('button')||e.button!==0)return;swipe={x:e.clientX,y:e.clientY};});el.addEventListener('pointerup',e=>{if(!swipe)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.3)choose(dx>0?1:0);});el.addEventListener('pointercancel',()=>swipe=null);}
function shareText(){const e=endingInfo(),u=location.protocol.startsWith('http')?location.href.split('?')[0].split('#')[0]:'';return {title:'인류 패치노트',text:`${e.icon} ${e.name}\n문명 ${fmt(s.score)}점 · 위기 ${s.clears}/3\n${s.rules.map(r=>HP.RULES[r.id].i+' '+HP.RULES[r.id].n).join(' + ')}\n실험 ${s.seed.toString(36).toUpperCase()}`,url:u};}
async function share(){const data=shareText();try{if(navigator.share){await navigator.share(data);return;}}catch(e){if(e.name==='AbortError')return;}const text=data.text+'\n'+data.url;try{await navigator.clipboard.writeText(text);toast('결과와 주소를 복사했습니다.');}catch(e){modal('결과 복사',`<p>아래 텍스트를 길게 눌러 복사하세요.</p><textarea style="width:100%;height:160px;font:inherit" readonly>${esc(text)}</textarea>`);}}
function exportRun(){const b=new Blob([JSON.stringify({version:2,run:s,best:meta.best},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='humanity-patchnotes-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b||b.disabled)return;const a=b.dataset.act;if(a==='close')return close();if(a==='choose')return choose(Number(b.dataset.side));if(a==='replace'){const side=pending,id=b.dataset.id;close();return choose(side,id);}if(a==='new'){if(s&&s.phase!=='end'&&screen==='home'){modal('새 실험을 시작할까요?','<p>진행 중인 실험은 새 실험으로 바뀝니다. 도감과 최고 기록은 유지됩니다.</p><button class="primary" data-act="confirmNew">새 실험 시작</button>');return;}return newGame();}if(a==='confirmNew'){close();return newGame();}if(a==='resume'){screen='game';return render();}if(a==='home')return home();if(a==='next')return next();if(a==='collection')return collection();if(a==='rule')return showRule(b.dataset.id);if(a==='settings')return settings();if(a==='share')return share();if(a==='export')return exportRun();if(a==='reroll'&&!busy){if(HP.reroll(s)){persist();render();beep('ok');}return;}if(a==='undo'&&!busy){const prior=HP.undo(s);if(prior){s=prior;persist();render();toast('한 번 되돌렸습니다. 같은 선택은 같은 판정입니다.');}return;}if(a==='sound'){meta.sound=!meta.sound;persist();b.textContent=meta.sound?'켜짐':'꺼짐';beep('ok');}if(a==='motion'){meta.reduced=!meta.reduced;persist();b.textContent=meta.reduced?'켜짐':'시스템 설정';}});
document.addEventListener('keydown',e=>{if($('dialog').open||screen!=='game'||!s||busy||e.repeat||e.target.closest('input,textarea'))return;if(s.phase==='result'&&!e.target.closest('button')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();next();}else if(s.phase==='choose'&&['ArrowLeft','ArrowRight','1','2'].includes(e.key)){e.preventDefault();choose(e.key==='ArrowLeft'||e.key==='1'?0:1);}});
$('dialog').addEventListener('cancel',()=>pending=null);document.addEventListener('visibilitychange',()=>{if(document.hidden&&context)context.suspend();});
persist();home();
